name: testing-pipe

on:
  pull_request:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Get last tag
      id: last_tag
      run: echo "::set-output name=tag::$(git describe --abbrev=0 --tags)"

    - name: Determine next tag
      id: next_tag
      run: echo "::set-output name=tag::build-0.0.$(echo "${{ steps.last_tag.outputs.tag }}" | awk -F '.' '{print $3+1}')"

    - name: Create and push tag
      run: |
        git tag ${{ steps.next_tag.outputs.tag }}
        git push origin ${{ steps.next_tag.outputs.tag }}
