name: testing-tags
on:
  push:
    branches:
      - main

jobs:
  tag_job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get existing tags
      id: get_tags
      run: |
        highest_tag=$(echo "$tags" | sort -Vr | head -n1)
        current_k=$(echo "$highest_tag" | sed 's/build-0.0.//')
        next_k=$((current_k + 1))
        echo NEXT_TAG="build-0.0.$next_k"

    - name: Create and push tag
      run: |
        git tag $NEXT_TAG
        git push origin $NEXT_TAG
