name: testing-tags
on:
  push:
    branches:
      - main

jobs:
  tag_job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get existing tags
      id: get_tags
      run: |
        tags=$(git tag --list "build-0.0.*" --sort=-v:refname)
        highest_tag=$(echo "$tags" | sort -Vr | head -n1)
        current_version=$(echo "$highest_tag" | awk -F '.' '{print $3}')
        next_version=$((current_version + 1))
        next_tag="build-0.0.$next_version"
        echo "::set-output name=next_tag::$next_tag"

    - name: Create and push new tag
      if: ${{ steps.get_tags.outputs.next_tag != '' }}
      run: |
        git tag ${{ steps.get_tags.outputs.next_tag }}
        git push origin ${{ steps.get_tags.outputs.next_tag }}
