name: testing-pipe

on:
  push:
    branches: main

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check if any tags exist
        id: check_tags
        run: |
          tag_count=$(git tag --list "build-0.0.*" | wc -l)
          if [ "$tag_count" -eq 0 ]; then
            echo "::set-output name=last_tag::build-0.0.0"
          else
            last_tag=$(git describe --match "build-0.0.*" --abbrev=0 --tags)
            last_digit=$(echo "$last_tag" | awk -F '.' '{print $NF}')
            next_digit=$((last_digit + 1))
            next_tag="build-0.0.$next_digit"
            echo "::set-output name=last_tag::$next_tag"
          fi

      - name: Create and push tag
        run: |
          git tag ${{ steps.check_tags.outputs.last_tag }}
          git push origin ${{ steps.check_tags.outputs.last_tag }}
