name: testing-pipe

on:
  pull_request:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Get last tag
      id: last_tag
      run: |
        last_tag=$(git for-each-ref --sort=-taggerdate --format '%(refname)' --count=1 'refs/tags/build-0.0.*')
        k=$(echo "$last_tag" | sed 's|refs/tags/build-0.0.||')
        next_k=$((k + 1))
        next_tag="build-0.0.$next_k"
        echo "::set-output name=tag::$next_tag"

    - name: Create and push tag
      run: |
        git tag ${{ steps.last_tag.outputs.tag }}
        git push origin ${{ steps.last_tag.outputs.tag }}
