name: tags

on:
  push:
    branches:
      - main

jobs:
  create-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get latest tag
        id: latest_tag
        run: |
          response=$(curl -s "https://api.github.com/repos/${{ github.repository }}/tags?per_page=1" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}")
          latest_tag=$(echo "$response" | jq -r '.[0].name')
          echo "::set-output name=tag::$latest_tag"
          last_tag=${{ steps.latest_tag.outputs.tag }}
          if [ -z "$last_tag" ]; then
            next_tag="build-0.0.0"
          else
            current_version=$(echo "$last_tag" | awk -F '.' '{print $3}')
            next_version=$((current_version + 1))
            next_tag="build-0.0.${next_version}"
          fi
          echo "::set-output name=tag::$next_tag"
          next_tag=${{ steps.next_tag.outputs.tag }}
          git tag $next_tag
          git push origin $next_tag
