name: tagging

on:
  push:
    branches:
      - main

jobs:
  create_tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Get Latest Tag
        id: get_latest_tag
        run: |
          latest_tag=$(git describe --match "build-0.0.*" --abbrev=0 --tags 2>/dev/null)
          current_version=$(echo "$latest_tag" | awk -F '.' '{print $3}')
          next_version=$((current_version + 1))
          echo "::set-output name=next_version::${next_version}"

      - name: Create and Push Tag
        id: create_tag
        run: |
          next_tag="build-0.0.${{ steps.get_latest_tag.outputs.next_version }}"
          git tag "$next_tag"
          git push origin "$next_tag"
