name: testing-pipe

on:
  push:
    branches: main

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get last tag
        id: last_tag
        run: |
          last_tag=$(git tag --list 'build-0.0.*' --sort=-version:refname | head -n1)
          if [[ -z "$last_tag" ]]; then
            next_tag="build-0.0.0"
          else
            last_digit=$(echo "$last_tag" | sed 's/build-0.0.//')
            next_digit=$((last_digit + 1))
            next_tag="build-0.0.$next_digit"
          fi
          echo "::set-output name=tag::$next_tag"

      - name: Create and push tag
        run: |
          git tag ${{ steps.last_tag.outputs.tag }}
          git push origin ${{ steps.last_tag.outputs.tag }}
