name: tags

on:
  push:
    branches:
      - main

jobs:
  create-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create and push tag
        run: |
          LAST_TAG=$(git tag -l --sort=-v:refname | head -n 1)
          LAST_VERSION=$(echo $LAST_TAG | sed 's/build-//')
          if [ -z ${LAST_VERSION+x} ]; then LAST_VERSION="0.0"; fi
          declare -a ARR=($(echo $LAST_VERSION| sed -e s/build-//g | tr -s "." " " | xargs -n 1))
          MAJOR=${ARR[0]}
          MINOR=${ARR[1]}
          NEXT_MINOR=$((MINOR + 1))
          NEXT_VERSION="$MAJOR.$MINOR"
          TAG_NAME="build-$NEXT_VERSION"
          git tag $TAG_NAME
          git push --tags
